export const dbName = 'smc-journal-db';
export const dbVersion = 3;
export const tradeStoreName = 'trades';
export const assetStoreName = 'assets';
export const modelStoreName = 'models';
export const settingsStoreName = 'settings';
export const aiConfigKey = 'ai-config';

export const defaultAiConfig = {
  enabled: true,
  provider: 'OpenAI',
  model: 'gpt-4.1-mini',
  baseUrl: 'https://api.openai.com/v1',
  apiKey: '',
  systemPrompt: '你是一个交易复盘助手，只基于用户提供的订单、截图和规则进行总结，不给投资建议。',
};

export const tagPresets = ['扫流', 'FVG', 'OB', 'ChoCH', 'Breaker', '顺势', '逆势', '待结果', '复盘'];

export const seedModels = [
  {
    id: 'model-liquidity-sweep-choch',
    name: 'Liquidity Sweep + ChoCH',
    title: '反转模型',
    favorite: true,
    accent: 'cyan',
    referenceImage: 'liquidity-sweep-choch',
    logic: '价格先扫掉前低或前高的流动性，制造假突破；随后快速收回并打破相反方向的小结构，形成 ChoCH，说明订单流可能短线反转。',
    points: ['高周期位于 Discount 区或需求区附近', '价格向下扫前低，等待低点附近推低点', '扫低后快速收回', '向上突破最近高点或形成 ChoCH', '回踩 FVG / OB / 结构位较多'],
    triggers: ['扫低后强阳收回关键低点', 'ChoCH 后回踩 FVG / OB 入场', '小级别再 BOS 后入场'],
    fail: '扫低后继续下跌不收回；回踩区域被快速跌破；入场后重新跌破 Sweep Low。',
    keyPoints: ['不要见到刺破前低就立刻做多', '确认入场通常在 ChoCH 后第一次回踩', '止损放 Sweep Low 下方'],
  },
  {
    id: 'model-fvg-continuation',
    name: 'FVG Continuation',
    title: '顺势延续模型',
    favorite: true,
    accent: 'emerald',
    referenceImage: 'fvg-continuation',
    logic: '趋势中强推动形成 FVG，不平衡区域在回踩时提供顺势延续机会。',
    points: ['高周期方向看多，结构保持 Higher High / Higher Low', '强势上涨推动留下明显 Bullish FVG', '推动后完成 BOS', '回踩进入 FVG 50% 或下沿，但不跌破前起点', '小周期出现拒绝下跌 / 反包 / BOS'],
    triggers: ['FVG 50% 附近出现较多结构', 'FVG 下沿出现下影线或强阳反包', '小周期从 FVG 内向上 BOS'],
    fail: 'FVG 被完全填补后继续下破；跌破推动起点；FVG 内长时间横盘无反应。',
    keyPoints: ['必须有趋势背景', '最好配合 BOS：先 BOS，再靠 FVG 回踩', 'FVG 靠近 Discount、OB、结构位时质量更高'],
  },
  {
    id: 'model-ob-reversal',
    name: 'OB Reversal',
    title: 'Order Block Mitigation 回踩模型',
    favorite: true,
    accent: 'amber',
    referenceImage: 'ob-reversal',
    logic: '价格在某区域完成吸筹或派发后出现强推动并打破结构，未来第一次回踩该 OB 时可能出现二次反应。',
    points: ['找到上涨推动前最后一根明显 bearish candle', 'OB 之后出现强推动，不是普通小反弹', '推动打破结构高点，形成 BOS 或 ChoCH', '回踩 OB 时最好位于 Discount 区', '小周期出现拒绝 / 反包 / BOS / ChoCH'],
    triggers: ['第一次回踩未测试过的 OB', 'OB 与 FVG、结构位、扫流动性共振', '小周期从 OB 内部转多'],
    fail: 'OB 被实体完全跌破；多次回踩反应减弱；OB 后推动没有破结构。',
    keyPoints: ['不是所有最后一根反向 K 都是 OB', '第一次回踩价值更高', '最好结合 Sweep、FVG、BOS / ChoCH'],
  },
  {
    id: 'model-breaker-retest',
    name: 'BOS Pullback',
    title: '顺势结构模型',
    favorite: true,
    accent: 'rose',
    referenceImage: 'bos-pullback',
    logic: '趋势中的价格突破前结构高点形成 BOS，说明方向向上；随后等回踩结构位、FVG 或 OB 再顺势入场。',
    points: ['高周期方向看多', '价格形成 Higher Low 后突破前高，出现 BOS', 'BOS 以实体突破而不是单纯影线', 'BOS 后回踩不破前一个 Higher Low', '回踩区域以内周期给出强信号'],
    triggers: ['回踩 BOS 结构位获得支撑', '回踩 FVG / OB 后出现小周期 BOS', '回踩中扫掉弱低点后快速收回'],
    fail: 'BOS 后迅速跌破区间；回踩跌破 Higher Low；回踩区反复反应后继续下破。',
    keyPoints: ['BOS 是方向确认，不是追单信号', '最好的交易发生在 BOS 后回踩', '更适合趋势行情'],
  },
  {
    id: 'model-inducement-sweep-poi',
    name: 'Inducement + Sweep + POI',
    title: '精准入场模型',
    favorite: true,
    accent: 'cyan',
    referenceImage: 'inducement-sweep-poi',
    logic: '真正 POI 前方先制造诱导高低点，引诱提前入场或止损集中；随后价格扫描 inducement，再进入真正 POI 并反转。',
    points: ['高周期有明确需求 POI', 'POI 上方形成诱导低点', '价格到达 inducement low', '随后进入真正 POI', '小周期出现 ChoCH 或 BOS'],
    triggers: ['扫诱导低点后快速收回', 'POI 内强阳反包', '回踩小 FVG 后入场'],
    fail: '扫单后未进入 POI；POI 被多次测试；POI 内无反应直接跌破。',
    keyPoints: ['真正优质位置通常在 inducement 后面', '不要在诱导点提前进场'],
  },
  {
    id: 'model-breaker-block',
    name: 'Breaker Block',
    title: '反转延续模型',
    favorite: true,
    accent: 'emerald',
    referenceImage: 'breaker-block',
    logic: '原本有效的 OB 被突破后角色转换，未来回踩时可能变成反向支撑或阻力。',
    points: ['原先存在 bearish OB / 供应区', '价格强势突破并形成 BOS', '被突破区域转换为 Bullish Breaker', '回踩时出现反应', '小周期转强'],
    triggers: ['回踩 Breaker 后形成下跌衰竭', '小周期 ChoCH / BOS', '与 FVG、结构位、Discount 共振'],
    fail: '回踩时重新跌回供应区下方；区域无反应；突破动能不足。',
    keyPoints: ['先有明确突破，再谈 Breaker', '回踩时最好等低周期确认'],
  },
  {
    id: 'model-equal-highs-lows-run',
    name: 'Equal Highs / Equal Lows Liquidity Run',
    title: '流动性扫单模型',
    favorite: true,
    accent: 'rose',
    referenceImage: 'equal-highs-lows-run',
    logic: '等高或等低是明显流动性池，价格常先扫单，再选择真正方向。',
    points: ['上方存在 Equal Highs 或下方存在 Equal Lows', '价格向上测试等高或向下测试等低', '刺破后不能继续上派或下派而快速收回', '小周期出现 ChoCH', '回踩 bearish FVG / OB 或 bullish FVG / OB 确定'],
    triggers: ['扫等高后强阴收回', '跌破结构低点形成 ChoCH', '回踩 FVG / OB 出现拒绝'],
    fail: '扫等高后继续站稳上方；ChoCH 失败；上方还有更大级别流动性。',
    keyPoints: ['等高/等低是目标区域，但不是天然反转位', '必须看收回和结构改变'],
  },
];

export function mergeSeedModelDetails(storedModels = []) {
  if (!storedModels.length) return seedModels;
  const storedById = new Map(storedModels.map((model) => [model.id, model]));
  const storedByName = new Map(storedModels.map((model) => [model.name, model]));
  const mergedSeeds = seedModels.map((seed) => {
    const stored = storedById.get(seed.id) || storedByName.get(seed.name);
    return stored
      ? {
          ...seed,
          ...stored,
          referenceImage: seed.referenceImage,
          points: stored.points?.length ? stored.points : seed.points,
          triggers: stored.triggers?.length ? stored.triggers : seed.triggers,
          keyPoints: stored.keyPoints?.length ? stored.keyPoints : seed.keyPoints,
          fail: stored.fail || seed.fail,
        }
      : seed;
  });
  const knownIds = new Set(seedModels.map((model) => model.id));
  const customModels = storedModels.filter((model) => !knownIds.has(model.id));
  return [...mergedSeeds, ...customModels];
}

export const seedTrades = [
  {
    id: 'T-240531-1',
    date: '2024-05-31T15:42',
    symbol: 'EUR/USD',
    timeframe: '1H',
    direction: '多',
    model: 'Liquidity Sweep + ChoCH',
    entry: '1.08234',
    stop: '1.07834',
    target: '1.09034',
    rMultiple: 2,
    position: '1.00',
    leverage: '100',
    risk: '100',
    profit: '200',
    closePrice: '1.09034',
    closedAt: '2024-05-31T18:20',
    result: 'win',
    tags: ['扫流', 'FVG1'],
    note: '流动性扫完后出现 ChoCH，回踩 FVG 后确认。',
    plan: '等待 FVG 回补后再次入场，清点正常。',
    review: '执行基本符合计划，出场可以再耐心。',
    checklist: ['趋势方向确认', '风险收益比合格', '入场后按计划管理'],
    image: '',
  },
  {
    id: 'T-240531-2',
    date: '2024-05-31T10:15',
    symbol: 'NAS100',
    timeframe: '5M',
    direction: '空',
    model: 'FVG Continuation',
    entry: '18942.25',
    stop: '18962.25',
    target: '18642.25',
    rMultiple: 2.5,
    position: '0.50',
    leverage: '100',
    risk: '80',
    profit: '200',
    closePrice: '18642.25',
    closedAt: '2024-05-31T11:30',
    result: 'win',
    tags: ['FVG', '顺势'],
    note: '顺势缺口延续，入场后没有回到结构上方。',
    plan: '等回补缺口中位再做空。',
    review: '入场位置好，但减仓记录不够细。',
    checklist: ['趋势方向确认', '风险收益比合格'],
    image: '',
  },
  {
    id: 'T-240530-1',
    date: '2024-05-30T22:05',
    symbol: 'XAU/USD',
    timeframe: '15M',
    direction: '多',
    model: 'OB Reversal',
    entry: '2345.12',
    stop: '2326.12',
    target: '2360.12',
    rMultiple: 2,
    position: '0.20',
    leverage: '50',
    risk: '120',
    profit: '',
    closePrice: '',
    closedAt: '',
    result: 'pending',
    tags: ['OB', '待结果'],
    note: '订单已建立，等待纽约盘后半段结果。',
    plan: '若跌破 OB 外侧直接止损，不提前移动止损。',
    review: '',
    checklist: ['风险收益比合格', '等待确认信号'],
    image: '',
  },
  {
    id: 'T-240530-2',
    date: '2024-05-30T16:30',
    symbol: 'GBP/USD',
    timeframe: '1H',
    direction: '多',
    model: 'Breaker Retest',
    entry: '1.27123',
    stop: '1.26763',
    target: '1.28123',
    rMultiple: 2,
    position: '1.00',
    leverage: '100',
    risk: '100',
    profit: '-100',
    closePrice: '1.26763',
    closedAt: '2024-05-30T18:10',
    result: 'loss',
    tags: ['Breaker', '复盘'],
    note: 'Breaker retest 过早入场，小级别确认不足。',
    plan: '等待回踩后确认。',
    review: '亏损来自确认不足，下一次要等小级别结构转换。',
    checklist: ['风险收益比合格'],
    image: '',
  },
];

export const emptyForm = {
  symbol: 'EUR/USD',
  timeframe: '1H',
  direction: '多',
  model: seedModels[0].name,
  entry: '',
  stop: '',
  target: '',
  rMultiple: '2.00',
  position: '0.01',
  leverage: '100',
  risk: '100',
  profit: '',
  closePrice: '',
  closedAt: '',
  result: 'pending',
  tags: '',
  plan: '',
  note: '',
  review: '',
  checklist: ['趋势方向确认', '风险收益比合格'],
  image: '',
  imageAssetId: '',
  imageName: '',
  imageMime: '',
  imageSize: 0,
  entryImage: '',
  entryImageAssetId: '',
  entryImageName: '',
  entryImageMime: '',
  entryImageSize: 0,
  closeImage: '',
  closeImageAssetId: '',
  closeImageName: '',
  closeImageMime: '',
  closeImageSize: 0,
};
